#!/usr/bin/env bash

# Transfer a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Check if the file exists
if [ ! -f "$FILE_PATH" ]; then
    echo "Error: File $FILE_PATH not found."
    exit 1
fi

# Transfer file using SCP
if [ "$#" -eq 4 ]; then
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$IP":~/
else
    echo "Error: Invalid number of arguments."
    exit 1
fi

# Check SCP exit status
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
    exit 1
fi
