#!/usr/bin/env bash

# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configuring Nginx for custom error handling
sudo bash -c 'cat <<EOF > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
    
    error_page 404 /404.html;
    location = /404.html {
	root /var/www/html;
	internal;
    }	

} 
EOF'

# Testing configurations for syntax errors
sudo nginx -t

# Restarting Nginx after implementing changes
sudo service nginx restart
