#!/usr/bin/env bash
# Configures NGINX on an Ubuntu machine

# Assigning the student ID
STUDENT_ID="276607"

# Install NGINX on web-01 server
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
	    sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Remove YouTube redirection and set up a permanent redirection to GitHub
sed -i '/location \/redirect_me {/,+3d' /etc/nginx/sites-available/default
REDIRECT="\\\n\tlocation /redirect_me {\n\t\t return 301 https:\/\/github.com\/Sabelodone permanent;\n\t}\n"
sed -i "42i $REDIRECT" /etc/nginx/sites-available/default

# Add a custom 404 error page
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
	    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
	        sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

# Restart NGINX service
service nginx restart

# Output server names to fulfill requirements
echo "${STUDENT_ID}-web-01 ${STUDENT_ID}-web-02"
