#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Assigning the student ID
STUDENT_ID="276607"

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo pt-get -y install haproxy

# edit config file
server_config=\
"
frontend Sabelodo.com.ng
        bind *:8080
        mode http
        default_backend Sabelodone.com.ng_backend
backend Sabelodone.com.ng_backend
        balance roundrobin
        server 276607-web-01 3.90.85.181:8080 check
        server 276607-web-02 35.175.104.3:8080 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart

# Output server names to fulfill requirements
echo "${STUDENT_ID}-web-01 ${STUDENT_ID}-web-02"
